product_bundles:
  online_course: online_course
  book: 0
  default: 0
negate_product_bundles: 0
redirection_route_path: checkout
redirection_route_path_other: ''
add_to_cart_replacement_text: Matricularme
clear_cart_before_add: 1
