_core:
  default_config_hash: 3RT89ubq8YS14GC2HtkB-Z2_tyW6ang7-04HFqMO6lI
langcode: es
registration: with-pass
registration_ftll_expire: false
registration_ftll_timeout: 86400
notify:
  register_confirmation_with_pass: true
registration_redirect: ''
